version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zacks-vizr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p7hg4lqr2cc"
s3_prefix = "zacks-vizr"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

